SELECT TOP (1000) [ID]
      ,[Last]
      ,[First]
      ,[Appearances]
      ,[Starts]
      ,[Wins]
      ,[Losses]
      ,[Saves]
      ,[WHIP]
      ,[ERA]
      ,[IP]
      ,[Hits]
      ,[BBs]
      ,[Ks]
      ,[HBP]
      ,[HRA]
      ,[Runs]
      ,[Earned_Runs]
      ,[Complete_Games]
      ,[Shutouts]
      ,[WP]
      ,[BK]
  FROM [StratBB].[dbo].[Pitching Stats]
  order by last;